@BACKEND_URL = http://backofficeapi-dev.nextlms.us
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyYWJpaEBhY2VtZXRlci5jb20iLCJqdGkiOiI0ZWE4ZWE3MS02YzgwLTRmZmMtYTJjMy0wYTMzODM2MDAyNmYiLCJleHAiOjE2OTgzMjI2MjAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDozMDAwIn0.AVzgF63eHYcAFs72wPlGbX1eTdR3SCQOU0vUDyvr3Bk
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyYWJpaEBhY2VtZXRlci5jb20iLCJqdGkiOiJmN2M3Mjg4OC1lN2Q3LTQyYjItYmVjMy02YmM0N2I2ODllN2YiLCJleHAiOjE2OTg5MjU2MjAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDozMDAwIn0.nASZSfJOs3MxcajZ0MBmp4Kwuq3INr4jvQHH07zh95M

@username = rabih@acemeter.com
@password = pass123%2B

### User login
GET {{BACKEND_URL}}/api/Login/GetLogin?username={{username}}&password={{password}}

### User token refresh
GET {{BACKEND_URL}}/api/Login/refreshtoken?refreshToken={{token}}
